package com.mannanlive.ebay.collections.sm

import com.mannanlive.ebay.collections.Card
import com.mannanlive.ebay.collections.CardType
import com.mannanlive.ebay.collections.SeriesCollection
import com.mannanlive.ebay.collections.SeriesCollector

class SunMoonHiddenFates {
    companion object {
        val collection = SeriesCollection(
            "SM115",
            listOf(
                Card(6, "Pinsir GX", CardType.GX),
                Card(7, "Charmander", CardType.NORMAL),
                Card(8, "Charmeleon", CardType.NORMAL),
                Card(9, "Charizard GX", CardType.GX),
                Card(14, "Starmie GX", CardType.GX),
                Card(16, "Gyarados GX", CardType.GX),
                Card(17, "Lapras", CardType.NORMAL),
                Card(31, "Mewtwo GX", CardType.GX),
                Card(32, "Mew", CardType.NORMAL),
                Card(36, "Onix GX", CardType.GX),
                Card(42, "Wigglytuff GX", CardType.GX),
                Card(44, "Moltres & Zapdos & Articuno GX", CardType.GX),
                Card(66, "Moltres & Zapdos & Articuno GX", CardType.FULL_ART),
                Card(67, "Giovanni's Exile", CardType.FULL_ART),
                Card(68, "Jessie & James", CardType.FULL_ART),
                Card(69, "Moltres & Zapdos & Articuno GX", CardType.HYPER_RARE),
                Card(1, "Scyther", CardType.SHINY, prefix = "SV"),
                Card(2, "Rowlet", CardType.SHINY, prefix = "SV"),
                Card(3, "Dartrix", CardType.SHINY, prefix = "SV"),
                Card(4, "Wimpod", CardType.SHINY, prefix = "SV"),
                Card(5, "Pheromosa", CardType.SHINY, prefix = "SV"),
                Card(6, "Charmander", CardType.SHINY, prefix = "SV"),
                Card(7, "Charmeleon", CardType.SHINY, prefix = "SV"),
                Card(8, "Alolan Vulpix", CardType.SHINY, prefix = "SV"),
                Card(9, "Wooper", CardType.SHINY, prefix = "SV"),
                Card(10, "Quagsire", CardType.SHINY, prefix = "SV"),
                Card(11, "Froakie", CardType.SHINY, prefix = "SV"),
                Card(12, "Frogadier", CardType.SHINY, prefix = "SV"),
                Card(13, "Voltorb", CardType.SHINY, prefix = "SV"),
                Card(14, "Xurkitree", CardType.SHINY, prefix = "SV"),
                Card(15, "Seviper", CardType.SHINY, prefix = "SV"),
                Card(16, "Shuppet", CardType.SHINY, prefix = "SV"),
                Card(17, "Inkay", CardType.SHINY, prefix = "SV"),
                Card(18, "Malamar", CardType.SHINY, prefix = "SV"),
                Card(19, "Poipole", CardType.SHINY, prefix = "SV"),
                Card(20, "Sudowoodo", CardType.SHINY, prefix = "SV"),
                Card(21, "Riolu", CardType.SHINY, prefix = "SV"),
                Card(22, "Lucario", CardType.SHINY, prefix = "SV"),
                Card(23, "Rockruff", CardType.SHINY, prefix = "SV"),
                Card(24, "Buzzwole", CardType.SHINY, prefix = "SV"),
                Card(25, "Zorua", CardType.SHINY, prefix = "SV"),
                Card(26, "Guzzlord", CardType.SHINY, prefix = "SV"),
                Card(27, "Magnemite", CardType.SHINY, prefix = "SV"),
                Card(28, "Magneton", CardType.SHINY, prefix = "SV"),
                Card(29, "Magnezone", CardType.SHINY, prefix = "SV"),
                Card(30, "Beldum", CardType.SHINY, prefix = "SV"),
                Card(31, "Metang", CardType.SHINY, prefix = "SV"),
                Card(32, "Celesteela", CardType.SHINY, prefix = "SV"),
                Card(33, "Kartana", CardType.SHINY, prefix = "SV"),
                Card(34, "Ralts", CardType.SHINY, prefix = "SV"),
                Card(35, "Kirlia", CardType.SHINY, prefix = "SV"),
                Card(36, "Diancie", CardType.SHINY, prefix = "SV"),
                Card(37, "Altaria", CardType.SHINY, prefix = "SV"),
                Card(38, "Gible", CardType.SHINY, prefix = "SV"),
                Card(39, "Gabite", CardType.SHINY, prefix = "SV"),
                Card(40, "Garchomp", CardType.SHINY, prefix = "SV"),
                Card(41, "Eevee", CardType.SHINY, prefix = "SV"),
                Card(42, "Swablu", CardType.SHINY, prefix = "SV"),
                Card(43, "Noibat", CardType.SHINY, prefix = "SV"),
                Card(44, "Oranguru", CardType.SHINY, prefix = "SV"),
                Card(45, "Type: Null", CardType.SHINY, prefix = "SV"),
                Card(46, "Leafeon GX", CardType.SHINY_GX, prefix = "SV"),
                Card(47, "Decidueye GX", CardType.SHINY_GX, prefix = "SV"),
                Card(48, "Golisopod GX", CardType.SHINY_GX, prefix = "SV"),
                Card(49, "Charizard GX", CardType.SHINY_GX, prefix = "SV", ignoreTrades = listOf(
                    // fake
                    224233895766,
                    // graded
                    124603516624,
                    274709191471
                )),
                Card(50, "Ho-Oh GX", CardType.SHINY_GX, prefix = "SV"),
                Card(51, "Reshiram GX", CardType.SHINY_GX, prefix = "SV"),
                Card(52, "Turtonator GX", CardType.SHINY_GX, prefix = "SV"),
                Card(53, "Alolan Ninetales GX", CardType.SHINY_GX, prefix = "SV"),
                Card(54, "Articuno GX", CardType.SHINY_GX, prefix = "SV"),
                Card(55, "Glaceon GX", CardType.SHINY_GX, prefix = "SV"),
                Card(56, "Greninja GX", CardType.SHINY_GX, prefix = "SV"),
                Card(57, "Electrode GX", CardType.SHINY_GX, prefix = "SV"),
                Card(58, "Xurkitree GX", CardType.SHINY_GX, prefix = "SV"),
                Card(59, "Mewtwo GX", CardType.SHINY_GX, prefix = "SV"),
                Card(60, "Espeon GX", CardType.SHINY_GX, prefix = "SV"),
                Card(61, "Banette GX", CardType.SHINY_GX, prefix = "SV"),
                Card(62, "Nihilego GX", CardType.SHINY_GX, prefix = "SV"),
                Card(63, "Naganadel GX", CardType.SHINY_GX, prefix = "SV"),
                Card(64, "Lucario GX", CardType.SHINY_GX, prefix = "SV"),
                Card(65, "Zygarde GX", CardType.SHINY_GX, prefix = "SV"),
                Card(66, "Lycanroc GX", CardType.SHINY_GX, prefix = "SV"),
                Card(67, "Lycanroc GX", CardType.SHINY_GX, prefix = "SV"),
                Card(68, "Buzzwole GX", CardType.SHINY_GX, prefix = "SV"),
                Card(69, "Umbreon GX", CardType.SHINY_GX, prefix = "SV"),
                Card(70, "Darkrai GX", CardType.SHINY_GX, prefix = "SV"),
                Card(71, "Guzzlord GX", CardType.SHINY_GX, prefix = "SV"),
                Card(72, "Scizor GX", CardType.SHINY_GX, prefix = "SV"),
                Card(73, "Kartana GX", CardType.SHINY_GX, prefix = "SV"),
                Card(74, "Stakataka GX", CardType.SHINY_GX, prefix = "SV"),
                Card(75, "Gardevoir GX", CardType.SHINY_GX, prefix = "SV"),
                Card(76, "Sylveon GX", CardType.SHINY_GX, prefix = "SV"),
                Card(77, "Altaria GX", CardType.SHINY_GX, prefix = "SV"),
                Card(78, "Noivern GX", CardType.SHINY_GX, prefix = "SV"),
                Card(79, "Silvally GX", CardType.SHINY_GX, prefix = "SV"),
                Card(80, "Drampa GX", CardType.SHINY_GX, prefix = "SV"),
                Card(81, "Aether Foundation Employee", CardType.ULTRA, prefix = "SV"),
                Card(82, "Cynthia", CardType.ULTRA, prefix = "SV"),
                Card(83, "Fisherman", CardType.ULTRA, prefix = "SV"),
                Card(84, "Guzma", CardType.ULTRA, prefix = "SV"),
                Card(85, "Hiker", CardType.ULTRA, prefix = "SV"),
                Card(86, "Lady", CardType.ULTRA, prefix = "SV"),
                Card(87, "Aether Paradise Conservation Area", CardType.SECRET, prefix = "SV"),
                Card(88, "Brooklet Hill", CardType.SECRET, prefix = "SV"),
                Card(89, "Mt. Coronet", CardType.SECRET, prefix = "SV"),
                Card(90, "Shrine of Punishment", CardType.SECRET, prefix = "SV"),
                Card(91, "Tapu Bulu GX", CardType.SECRET, prefix = "SV"),
                Card(92, "Tapu Fini GX", CardType.SECRET, prefix = "SV"),
                Card(93, "Tapu Koko GX", CardType.SECRET, prefix = "SV"),
                Card(94, "Tapu Lele GX", CardType.SECRET, prefix = "SV")
            ),
            "Hidden%20Fates",
            listOf("jumbo", "promo","japanese", "bgs", "metal")
        )

        @JvmStatic
        fun main(args: Array<String>) {
            SeriesCollector().collect(collection)
        }
    }
}
