package com.mannanlive.ebay.collections

class SunMoonCosmicEclipse {
    companion object {
        val collection = SeriesCollection(
            "SM12",
            listOf(
                Card(1, "Venusaur & Snivy GX", CardType.GX),
                Card(4, "Vileplume GX", CardType.GX),
                Card(22, "Charizard & Braixen GX", CardType.GX),
                Card(35, "Volcarona GX", CardType.GX),
                Card(38, "Blastoise & Piplup GX", CardType.GX),
                Card(63, "Wishiwashi GX", CardType.GX),
                Card(75, "Solgaleo & Lunala GX", CardType.GX),
                Card(95, "Oricorio GX", CardType.GX),
                Card(110, "Flygon GX", CardType.GX),
                Card(129, "Alolan Persian GX", CardType.GX),
                Card(143, "Togepi & Cleffa & Igglybuff GX", CardType.GX),
                Card(156, "Arceus & Dialga & Palkia GX", CardType.GX),
                Card(157, "Reshiram & Zekrom GX", CardType.GX),
                Card(158, "Naganadel & Guzzlord GX", CardType.GX),
                Card(165, "Mega Lopunny & Jigglypuff GX", CardType.GX),
                Card(184, "Silvally GX", CardType.GX),
                Card(210, "Venusaur & Snivy GX", CardType.FULL_ART),
                Card(211, "Vileplume GX", CardType.FULL_ART),
                Card(212, "Charizard & Braixen GX", CardType.FULL_ART),
                Card(213, "Volcarona GX", CardType.FULL_ART),
                Card(214, "Blastoise & Piplup GX", CardType.FULL_ART),
                Card(215, "Blastoise & Piplup GX", CardType.FULL_ART),
                Card(216, "Solgaleo & Lunala GX", CardType.FULL_ART),
                Card(217, "Oricorio GX", CardType.FULL_ART),
                Card(218, "Flygon GX", CardType.FULL_ART),
                Card(219, "Alolan Persian GX", CardType.FULL_ART),
                Card(220, "Arceus & Dialga & Palkia GX", CardType.FULL_ART),
                Card(221, "Arceus & Dialga & Palkia GX", CardType.FULL_ART),
                Card(222, "Reshiram & Zekrom GX", CardType.FULL_ART),
                Card(223, "Naganadel & Guzzlord GX", CardType.FULL_ART),
                Card(224, "Naganadel & Guzzlord GX", CardType.FULL_ART),
                Card(225, "Mega Lopunny & Jigglypuff GX", CardType.FULL_ART),
                Card(226, "Mega Lopunny & Jigglypuff GX", CardType.FULL_ART),
                Card(227, "Silvally GX", CardType.FULL_ART),
                Card(228, "Cynthia & Caitlin", CardType.FULL_ART),
                Card(229, "Guzma & Hala", CardType.FULL_ART),
                Card(230, "Lillie's Full Force", CardType.FULL_ART),
                Card(231, "Mallow & Lana", CardType.FULL_ART),
                Card(232, "N's Resolve", CardType.FULL_ART),
                Card(233, "Professor Oak's Setup", CardType.FULL_ART),
                Card(234, "Red & Blue", CardType.FULL_ART),
                Card(235, "Roller Skater", CardType.FULL_ART),
                Card(236, "Rosa", CardType.FULL_ART),
                Card(237, "Torkoal", CardType.FULL_ART),
                Card(238, "Weavile", CardType.FULL_ART),
                Card(239, "Piplup", CardType.FULL_ART),
                Card(240, "Wishiwashi", CardType.FULL_ART),
                Card(241, "Pikachu", CardType.FULL_ART),
                Card(242, "Magnemite", CardType.FULL_ART),
                Card(243, "Koffing", CardType.FULL_ART),
                Card(244, "Gallade", CardType.FULL_ART),
                Card(245, "Mimikyu", CardType.FULL_ART),
                Card(246, "Excadrill", CardType.FULL_ART),
                Card(247, "Steelix", CardType.FULL_ART),
                Card(248, "Stoutland", CardType.FULL_ART),
                Card(249, "Venusaur & Snivy GX", CardType.HYPER_RARE),
                Card(250, "Vileplume GX", CardType.HYPER_RARE),
                Card(251, "Charizard & Braixen GX", CardType.HYPER_RARE),
                Card(252, "Volcarona GX", CardType.HYPER_RARE),
                Card(253, "Blastoise & Piplup GX", CardType.HYPER_RARE),
                Card(254, "Solgaleo & Lunala GX", CardType.HYPER_RARE),
                Card(255, "Oricorio GX", CardType.HYPER_RARE),
                Card(256, "Flygon GX", CardType.HYPER_RARE),
                Card(257, "Alolan Persian GX", CardType.HYPER_RARE),
                Card(258, "Arceus & Dialga & Palkia GX", CardType.HYPER_RARE),
                Card(259, "Reshiram & Zekrom GX", CardType.HYPER_RARE),
                Card(260, "Naganadel & Guzzlord GX", CardType.HYPER_RARE),
                Card(261, "Mega Lopunny & Jigglypuff GX", CardType.HYPER_RARE),
                Card(262, "Silvally GX", CardType.HYPER_RARE),
                Card(263, "Giant Hearth", CardType.SECRET_RARE),
                Card(264, "Great Catcher", CardType.SECRET_RARE),
                Card(265, "Island Challenge Amulet", CardType.SECRET_RARE),
                Card(266, "Lana's Fishing Rod", CardType.SECRET_RARE),
                Card(267, "Lillie's Poké Doll", CardType.SECRET_RARE),
                Card(268, "Martial Arts Dojo", CardType.SECRET_RARE),
                Card(269, "Power Plant", CardType.SECRET_RARE),
                Card(270, "Tag Call", CardType.SECRET_RARE),
                Card(271, "Draw Energy", CardType.SECRET_RARE)
            ),
            "cosmic",
            listOf("digital", "jumbo", "promo")
        )

        @JvmStatic
        fun main(args: Array<String>) = SeriesCollector().collect(collection)
    }
}
