package com.mannanlive.ebay.collections

class XyEvolutions {
    companion object {
        val collection = SeriesCollection(
            "XY12",
            listOf(
                Card(1, "Venusaur EX", CardType.EX),
                Card(2, "M Venusaur EX", CardType.MEGA_EX),
                Card(9, "Charmander", CardType.NORMAL),
                Card(10, "Charmeleon", CardType.NORMAL),
                Card(11, "Charizard", CardType.NORMAL, listOf(
                    193692682158,
                    264851427258,
                    264850483110,
                    264739377525,
                    203061425327,
                    274481445989,
                    //PSA
                    174483978035,
                    193710271029,
                    233734416973,
                    174483980058,
                    174483979161,
                    114462447190,
                    164449272200,
                    164445387262,
                    264794659113,
                    164406961897,
                    164406966255,
                    224179547582,
                    164377939311,
                    264850479441,
                    264866061795,
                    164382485512,
                    //multiple
                    283963637440,
                    184489075013,
                    383765414719
                )),
                Card(12, "Charizard EX", CardType.EX),
                Card(13, "M Charizard EX", CardType.MEGA_EX),
                Card(14, "Vulpix", CardType.NORMAL),
                Card(15, "Ninetales", CardType.NORMAL),
                Card(16, "Ninetales BREAK", CardType.BREAK),
                Card(17, "Growlithe", CardType.NORMAL),
                Card(18, "Arcanine", CardType.NORMAL),
                Card(19, "Ponyta", CardType.NORMAL),
                Card(20, "Magmar", CardType.NORMAL),
                Card(21, "Blastoise EX", CardType.EX),
                Card(22, "M Blastoise EX", CardType.MEGA_EX),
                Card(23, "Poliwag", CardType.NORMAL),
                Card(24, "Poliwhirl", CardType.NORMAL),
                Card(25, "Poliwrath", CardType.NORMAL),
                Card(26, "Slowbro EX", CardType.EX),
                Card(27, "M Slowbro EX", CardType.MEGA_EX),
                Card(28, "Seel", CardType.NORMAL),
                Card(29, "Dewgong", CardType.NORMAL),
                Card(30, "Staryu", CardType.NORMAL),
                Card(31, "Starmie", CardType.NORMAL),
                Card(32, "Starmie BREAK", CardType.BREAK),
                Card(33, "Magikarp", CardType.NORMAL),
                Card(34, "Gyarados", CardType.NORMAL),
                Card(35, "Pikachu", CardType.NORMAL),
                Card(36, "Raichu", CardType.NORMAL),
                Card(37, "Magnemite", CardType.NORMAL),
                Card(38, "Magneton", CardType.NORMAL),
                Card(39, "Voltorb", CardType.NORMAL),
                Card(40, "Electrode", CardType.NORMAL),
                Card(41, "Electabuzz", CardType.NORMAL),
                Card(42, "Zapdos", CardType.NORMAL),
                Card(43, "Nidoran ♂", CardType.NORMAL),
                Card(44, "Nidorino", CardType.NORMAL),
                Card(45, "Nidoking", CardType.NORMAL),
                Card(46, "Nidoking BREAK", CardType.BREAK),
                Card(47, "Gastly", CardType.NORMAL),
                Card(48, "Haunter", CardType.NORMAL),
                Card(49, "Drowzee", CardType.NORMAL),
                Card(50, "Koffing", CardType.NORMAL),
                Card(51, "Mewtwo", CardType.NORMAL),
                Card(52, "Mewtwo EX", CardType.EX),
                Card(53, "Mew", CardType.NORMAL),
                Card(54, "Sandshrew", CardType.NORMAL),
                Card(55, "Diglett", CardType.NORMAL),
                Card(56, "Dugtrio", CardType.NORMAL),
                Card(57, "Machop", CardType.NORMAL),
                Card(58, "Machoke", CardType.NORMAL),
                Card(59, "Machamp", CardType.NORMAL),
                Card(60, "Machamp BREAK", CardType.BREAK),
                Card(61, "Onix", CardType.NORMAL),
                Card(62, "Hitmonchan", CardType.NORMAL),
                Card(63, "Clefairy", CardType.NORMAL),
                Card(64, "Pidgeot EX", CardType.EX),
                Card(65, "M Pidgeot EX", CardType.MEGA_EX),
                Card(66, "Rattata", CardType.NORMAL),
                Card(67, "Raticate", CardType.NORMAL),
                Card(68, "Farfetch'd", CardType.NORMAL),
                Card(69, "Doduo", CardType.NORMAL),
                Card(70, "Chansey", CardType.NORMAL),
                Card(71, "Porygon", CardType.NORMAL),
                Card(72, "Dragonite EX", CardType.EX),
                Card(73, "Blastoise Spirit Link", CardType.NORMAL),
                Card(74, "Brock's Grit", CardType.NORMAL),
                Card(75, "Charizard Spirit Link", CardType.NORMAL),
                Card(76, "Devolution Spray", CardType.NORMAL),
                Card(77, "Energy Retrieval", CardType.NORMAL),
                Card(78, "Full Heal", CardType.NORMAL),
                Card(79, "Maintenance", CardType.NORMAL),
                Card(80, "Misty's Determination", CardType.NORMAL),
                Card(81, "Pidgeot Spirit Link", CardType.NORMAL),
                Card(82, "Pokedex", CardType.NORMAL),
                Card(83, "Potion", CardType.NORMAL),
                Card(84, "Professor Oak's Hint", CardType.NORMAL),
                Card(85, "Revive", CardType.NORMAL),
                Card(86, "Slowbro Spirit Link", CardType.NORMAL),
                Card(87, "Super Potion", CardType.NORMAL),
                Card(88, "Switch", CardType.NORMAL),
                Card(89, "Venusaur Spirit Link", CardType.NORMAL),
                Card(90, "Double Colorless Energy", CardType.NORMAL),
                Card(91, "Grass Energy", CardType.NORMAL),
                Card(100, "M Venusaur EX", CardType.FULL_ART),
                Card(101, "M Charizard EX", CardType.FULL_ART),
                Card(102, "M Blastoise EX", CardType.FULL_ART),
                Card(103, "Mewtwo EX", CardType.FULL_ART),
                Card(104, "Pidgeot EX", CardType.FULL_ART),
                Card(105, "M Pidgeot EX", CardType.FULL_ART),
                Card(106, "Dragonite EX", CardType.FULL_ART),
                Card(107, "Brock's Grit", CardType.FULL_ART),
                Card(108, "Misty's Determination", CardType.EX),
                Card(109, "Exeggutor", CardType.SECRET_RARE),
                Card(110, "Flying Pikachu", CardType.SECRET_RARE),
                Card(111, "Surfing Pikachu", CardType.SECRET_RARE),
                Card(112, "Imakuni's Doduo", CardType.SECRET_RARE),
                Card(113, "Here Comes Team Rocket!", CardType.SECRET_RARE)
            ),
            "evolutions",
            listOf("digital", "jumbo", "promo")
        )

        @JvmStatic
        fun main(args: Array<String>) = SeriesCollector().collect(collection)
    }
}
