package com.mannanlive.ebay.collections.swsh
    
import com.mannanlive.ebay.collections.Card
import com.mannanlive.ebay.collections.CardType
import com.mannanlive.ebay.collections.SeriesCollection
import com.mannanlive.ebay.collections.SeriesCollector

class SwordShieldShiningFates {
    companion object {
        val collection = SeriesCollection(
            "SWSH45",
            listOf(
                Card(9, "Dhelmise V", CardType.V),
                Card(10, "Dhelmise VMAX", CardType.VMAX),
                Card(17, "Reshiram", CardType.AMAZING_RARE),
                Card(18, "Cinderace V", CardType.V),
                Card(19, "Cinderace VMAX", CardType.VMAX),
                Card(21, "Kyogre", CardType.AMAZING_RARE),
                Card(37, "Morpeko V", CardType.V),
                Card(38, "Morpeko VMAX", CardType.VMAX),
                Card(39, "Indeedee V", CardType.V),
                Card(44, "Crobat V", CardType.V),
                Card(45, "Crobat VMAX", CardType.VMAX),
                Card(46, "Yveltal", CardType.AMAZING_RARE),
                Card(50, "Ditto V", CardType.V),
                Card(51, "Ditto VMAX", CardType.VMAX),
                Card(53, "Greedent V", CardType.V),
                Card(54, "Cramorant V", CardType.V),
                Card(55, "Cramorant VMAX", CardType.VMAX),
                Card(64, "Alcremie V", CardType.ULTRA),
                Card(65, "Ball Guy", CardType.ULTRA),
                Card(66, "Bird Keeper", CardType.ULTRA),
                Card(67, "Cara Liss", CardType.ULTRA),
                Card(68, "Gym Trainer", CardType.ULTRA),
                Card(69, "Piers", CardType.ULTRA),
                Card(70, "Poké Kid", CardType.ULTRA, "(Poké,Poke) Kid"),
                Card(71, "Rose", CardType.ULTRA),
                Card(72, "Skyla", CardType.ULTRA),
                Card(73, "Alcremie VMAX", CardType.RAINBOW),
                Card(1, "Rowlet", CardType.SHINY, prefix = "SV"),
                Card(2, "Dartrix", CardType.SHINY, prefix = "SV"),
                Card(3, "Decidueye", CardType.SHINY, prefix = "SV"),
                Card(4, "Grookey", CardType.SHINY, prefix = "SV"),
                Card(5, "Thwackey", CardType.SHINY, prefix = "SV"),
                Card(6, "Rillaboom", CardType.SHINY, prefix = "SV"),
                Card(7, "Blipbug", CardType.SHINY, prefix = "SV"),
                Card(8, "Dottler", CardType.SHINY, prefix = "SV"),
                Card(9, "Orbeetle", CardType.SHINY, prefix = "SV"),
                Card(10, "Gossifleur", CardType.SHINY, prefix = "SV"),
                Card(11, "Eldegoss", CardType.SHINY, prefix = "SV"),
                Card(12, "Applin", CardType.SHINY, prefix = "SV"),
                Card(13, "Flapple", CardType.SHINY, prefix = "SV"),
                Card(14, "Appletun", CardType.SHINY, prefix = "SV"),
                Card(15, "Scorbunny", CardType.SHINY, prefix = "SV"),
                Card(16, "Raboot", CardType.SHINY, prefix = "SV"),
                Card(17, "Cinderace", CardType.SHINY, prefix = "SV"),
                Card(18, "Sizzlipede", CardType.SHINY, prefix = "SV"),
                Card(19, "Centiskorch", CardType.SHINY, prefix = "SV"),
                Card(20, "Galarian Mr. Mime", CardType.SHINY, prefix = "SV"),
                Card(21, "Galarian Mr. Rime", CardType.SHINY, prefix = "SV"),
                Card(22, "Suicune", CardType.SHINY, prefix = "SV"),
                Card(23, "Galarian Darumaka", CardType.SHINY, prefix = "SV"),
                Card(24, "Galarian Darmanitan", CardType.SHINY, prefix = "SV"),
                Card(25, "Sobble", CardType.SHINY, prefix = "SV"),
                Card(26, "Drizzile", CardType.SHINY, prefix = "SV"),
                Card(27, "Inteleon", CardType.SHINY, prefix = "SV"),
                Card(28, "Chewtle", CardType.SHINY, prefix = "SV"),
                Card(29, "Drednaw", CardType.SHINY, prefix = "SV"),
                Card(30, "Cramorant", CardType.SHINY, prefix = "SV"),
                Card(31, "Arrokuda", CardType.SHINY, prefix = "SV"),
                Card(32, "Barraskewda", CardType.SHINY, prefix = "SV"),
                Card(33, "Snom", CardType.SHINY, prefix = "SV"),
                Card(34, "Frosmoth", CardType.SHINY, prefix = "SV"),
                Card(35, "Eiscue", CardType.SHINY, prefix = "SV"),
                Card(36, "Dracovish", CardType.SHINY, prefix = "SV"),
                Card(37, "Arctovish", CardType.SHINY, prefix = "SV"),
                Card(38, "Rotom", CardType.SHINY, prefix = "SV"),
                Card(39, "Yamper", CardType.SHINY, prefix = "SV"),
                Card(40, "Boltund", CardType.SHINY, prefix = "SV"),
                Card(41, "Toxel", CardType.SHINY, prefix = "SV"),
                Card(42, "Toxtricity", CardType.SHINY, prefix = "SV"),
                Card(43, "Pincurchin", CardType.SHINY, prefix = "SV"),
                Card(44, "Morpeko", CardType.SHINY, prefix = "SV"),
                Card(45, "Dracozolt", CardType.SHINY, prefix = "SV"),
                Card(46, "Arctozolt", CardType.SHINY, prefix = "SV"),
                Card(47, "Galarian Ponyta", CardType.SHINY, prefix = "SV"),
                Card(48, "Galarian Rapidash", CardType.SHINY, prefix = "SV"),
                Card(49, "Galarian Corsola", CardType.SHINY, prefix = "SV"),
                Card(50, "Galarian Cursola", CardType.SHINY, prefix = "SV"),
                Card(51, "Dedenne", CardType.SHINY, prefix = "SV"),
                Card(52, "Sinistea", CardType.SHINY, prefix = "SV"),
                Card(53, "Polteageist", CardType.SHINY, prefix = "SV"),
                Card(54, "Hatenna", CardType.SHINY, prefix = "SV"),
                Card(55, "Hattrem", CardType.SHINY, prefix = "SV"),
                Card(56, "Hatterene", CardType.SHINY, prefix = "SV"),
                Card(57, "Milcery", CardType.SHINY, prefix = "SV"),
                Card(58, "Alcremie", CardType.SHINY, prefix = "SV"),
                Card(59, "Indeedee", CardType.SHINY, prefix = "SV"),
                Card(60, "Dreepy", CardType.SHINY, prefix = "SV"),
                Card(61, "Drakloak", CardType.SHINY, prefix = "SV"),
                Card(62, "Dragapult", CardType.SHINY, prefix = "SV"),
                Card(63, "Galarian Farfetch'd", CardType.SHINY, prefix = "SV"),
                Card(64, "Galarian Sirfetch'd", CardType.SHINY, prefix = "SV"),
                Card(65, "Galarian Yamask", CardType.SHINY, prefix = "SV"),
                Card(66, "Galarian Runerigus", CardType.SHINY, prefix = "SV"),
                Card(67, "Rolycoly", CardType.SHINY, prefix = "SV"),
                Card(68, "Carkol", CardType.SHINY, prefix = "SV"),
                Card(69, "Coalossal", CardType.SHINY, prefix = "SV"),
                Card(70, "Silicobra", CardType.SHINY, prefix = "SV"),
                Card(71, "Sandaconda", CardType.SHINY, prefix = "SV"),
                Card(72, "Clobbopus", CardType.SHINY, prefix = "SV"),
                Card(73, "Grapploct", CardType.SHINY, prefix = "SV"),
                Card(74, "Falinks", CardType.SHINY, prefix = "SV"),
                Card(75, "Stonjourner", CardType.SHINY, prefix = "SV"),
                Card(76, "Koffing", CardType.SHINY, prefix = "SV"),
                Card(77, "Galarian Weezing", CardType.SHINY, prefix = "SV"),
                Card(78, "Galarian Zigzagoon", CardType.SHINY, prefix = "SV"),
                Card(79, "Galarian Linoone", CardType.SHINY, prefix = "SV"),
                Card(80, "Galarian Obstagoon", CardType.SHINY, prefix = "SV"),
                Card(81, "Nickit", CardType.SHINY, prefix = "SV"),
                Card(82, "Thievul", CardType.SHINY, prefix = "SV"),
                Card(83, "Impidimp", CardType.SHINY, prefix = "SV"),
                Card(84, "Morgrem", CardType.SHINY, prefix = "SV"),
                Card(85, "Grimmsnarl", CardType.SHINY, prefix = "SV"),
                Card(86, "Galarian Meowth", CardType.SHINY, prefix = "SV"),
                Card(87, "Galarian Perrserker", CardType.SHINY, prefix = "SV"),
                Card(88, "Galarian Stunfisk", CardType.SHINY, prefix = "SV"),
                Card(89, "Corviknight", CardType.SHINY, prefix = "SV"),
                Card(90, "Cufant", CardType.SHINY, prefix = "SV"),
                Card(91, "Copperajah", CardType.SHINY, prefix = "SV"),
                Card(92, "Duraludon", CardType.SHINY, prefix = "SV"),
                Card(93, "Minccino", CardType.SHINY, prefix = "SV"),
                Card(94, "Cinccino", CardType.SHINY, prefix = "SV"),
                Card(95, "Ducklett", CardType.SHINY, prefix = "SV"),
                Card(96, "Swanna", CardType.SHINY, prefix = "SV"),
                Card(97, "Bunnelby", CardType.SHINY, prefix = "SV"),
                Card(98, "Oranguru", CardType.SHINY, prefix = "SV"),
                Card(99, "Skwovet", CardType.SHINY, prefix = "SV"),
                Card(100, "Greedent", CardType.SHINY, prefix = "SV"),
                Card(101, "Rookidee", CardType.SHINY, prefix = "SV"),
                Card(102, "Corvisquire", CardType.SHINY, prefix = "SV"),
                Card(103, "Wooloo", CardType.SHINY, prefix = "SV"),
                Card(104, "Dubwool", CardType.SHINY, prefix = "SV"),
                Card(105, "Rillaboom V", CardType.V, prefix = "SV"),
                Card(106, "Rillaboom VMAX", CardType.VMAX, prefix = "SV"),
                Card(107, "Charizard VMAX", CardType.VMAX, prefix = "SV", ignoreTrades = listOf(
                    //graded
                    324596463013,
                    284264942789
                )),
                Card(108, "Centiskorch V", CardType.V, prefix = "SV"),
                Card(109, "Centiskorch VMAX", CardType.VMAX, prefix = "SV"),
                Card(110, "Lapras V", CardType.V, prefix = "SV"),
                Card(111, "Lapras VMAX", CardType.VMAX, prefix = "SV"),
                Card(112, "Toxtricity V", CardType.V, prefix = "SV"),
                Card(113, "Toxtricity VMAX", CardType.VMAX, prefix = "SV"),
                Card(114, "Indeedee V", CardType.V, prefix = "SV"),
                Card(115, "Falinks V", CardType.V, prefix = "SV"),
                Card(116, "Grimmsnarl V", CardType.V, prefix = "SV"),
                Card(117, "Grimmsnarl VMAX", CardType.VMAX, prefix = "SV"),
                Card(118, "Ditto V", CardType.V, prefix = "SV"),
                Card(119, "Ditto VMAX", CardType.VMAX, prefix = "SV"),
                Card(120, "Dubwool V", CardType.V, prefix = "SV"),
                Card(121, "Eternatus V", CardType.SECRET, prefix = "SV"),
                Card(122, "Eternatus VMAX", CardType.SECRET, prefix = "SV")
            ),
            "Shining%20Fates",
            listOf("jumbo", "promo","japanese")
        )

        @JvmStatic
        fun main(args: Array<String>) {
            SeriesCollector().collect(collection)
        }
    }
}
