package com.mannanlive.ebay.collections.swsh
    
import com.mannanlive.ebay.collections.Card
import com.mannanlive.ebay.collections.CardType
import com.mannanlive.ebay.collections.SeriesCollection
import com.mannanlive.ebay.collections.SeriesCollector

class SwordShieldEvolvingSkies {
    companion object {
        val collection = SeriesCollection(
            "SWSH7",
            listOf(
                Card(7, "Leafeon V", CardType.V),
                Card(8, "Leafeon VMAX", CardType.VMAX),
                Card(13, "Trevenant V", CardType.V),
                Card(14, "Trevenant VMAX", CardType.VMAX),
                Card(18, "Flareon VMAX", CardType.VMAX),
                Card(21, "Volcarona V", CardType.V),
                Card(28, "Gyarados V", CardType.V),
                Card(29, "Gyarados VMAX", CardType.VMAX),
                Card(30, "Vaporeon VMAX", CardType.VMAX),
                Card(31, "Suicune V", CardType.V),
                Card(40, "Glaceon V", CardType.V),
                Card(41, "Glaceon VMAX", CardType.VMAX),
                Card(48, "Arctovish V", CardType.V),
                Card(51, "Jolteon VMAX", CardType.VMAX),
                Card(58, "Dracozolt V", CardType.V),
                Card(59, "Dracozolt VMAX", CardType.VMAX),
                Card(64, "Espeon V", CardType.V),
                Card(65, "Espeon VMAX", CardType.VMAX),
                Card(70, "Golurk V", CardType.V),
                Card(74, "Sylveon V", CardType.V),
                Card(75, "Sylveon VMAX", CardType.VMAX),
                Card(83, "Medicham V", CardType.V),
                Card(91, "Lycanroc V", CardType.V),
                Card(92, "Lycanroc VMAX", CardType.VMAX),
                Card(94, "Umbreon V", CardType.V),
                Card(95, "Umbreon VMAX", CardType.VMAX),
                Card(100, "Garbodor V", CardType.V),
                Card(101, "Garbodor VMAX", CardType.VMAX),
                Card(110, "Rayquaza V", CardType.V),
                Card(111, "Rayquaza VMAX", CardType.VMAX),
                Card(117, "Noivern V", CardType.V),
                Card(122, "Duraludon V", CardType.V),
                Card(123, "Duraludon VMAX", CardType.VMAX),
                Card(166, "Leafeon V", CardType.ULTRA),
                Card(167, "Leafeon V", CardType.ULTRA),
                Card(168, "Trevenant V", CardType.ULTRA),
                Card(169, "Flareon V", CardType.ULTRA),
                Card(170, "Volcarona V", CardType.ULTRA),
                Card(171, "Gyarados V", CardType.ULTRA),
                Card(172, "Vaporeon V", CardType.ULTRA),
                Card(173, "Suicune V", CardType.ULTRA),
                Card(174, "Glaceon V", CardType.ULTRA),
                Card(175, "Glaceon V", CardType.ULTRA),
                Card(176, "Arctovish V", CardType.ULTRA),
                Card(177, "Jolteon V", CardType.ULTRA),
                Card(178, "Dracozolt V", CardType.ULTRA),
                Card(179, "Espeon V", CardType.ULTRA),
                Card(180, "Espeon V", CardType.ULTRA),
                Card(181, "Golurk V", CardType.ULTRA),
                Card(182, "Golurk V", CardType.ULTRA),
                Card(183, "Sylveon V", CardType.ULTRA),
                Card(184, "Sylveon V", CardType.ULTRA),
                Card(185, "Medicham V", CardType.ULTRA),
                Card(186, "Medicham V", CardType.ULTRA),
                Card(187, "Lycanroc V", CardType.ULTRA),
                Card(188, "Umbreon V", CardType.ULTRA),
                Card(189, "Umbreon V", CardType.ULTRA),
                Card(190, "Garbodor V", CardType.ULTRA),
                Card(191, "Dragonite V", CardType.ULTRA),
                Card(192, "Dragonite V", CardType.ULTRA),
                Card(193, "Rayquaza V", CardType.ULTRA),
                Card(194, "Rayquaza V", CardType.ULTRA),
                Card(195, "Noivern V", CardType.ULTRA),
                Card(196, "Noivern V", CardType.ULTRA),
                Card(197, "Duraludon V", CardType.ULTRA),
                Card(198, "Duraludon V", CardType.ULTRA),
                Card(199, "Aroma Lady", CardType.ULTRA),
                Card(200, "Copycat", CardType.ULTRA),
                Card(201, "Gordie", CardType.ULTRA),
                Card(202, "Raihan", CardType.ULTRA),
                Card(203, "Zinnia's Resolve", CardType.ULTRA),
                Card(204, "Leafeon VMAX", CardType.RAINBOW),
                Card(205, "Leafeon VMAX", CardType.RAINBOW),
                Card(206, "Trevenant VMAX", CardType.RAINBOW),
                Card(207, "Gyarados VMAX", CardType.RAINBOW),
                Card(208, "Glaceon VMAX", CardType.RAINBOW),
                Card(209, "Glaceon VMAX", CardType.RAINBOW),
                Card(210, "Dracozolt VMAX", CardType.RAINBOW),
                Card(211, "Sylveon VMAX", CardType.RAINBOW),
                Card(212, "Sylveon VMAX", CardType.RAINBOW),
                Card(213, "Lycanroc VMAX", CardType.RAINBOW),
                Card(214, "Umbreon VMAX", CardType.RAINBOW),
                Card(215, "Umbreon VMAX", CardType.RAINBOW),
                Card(216, "Garbodor VMAX", CardType.RAINBOW),
                Card(217, "Rayquaza VMAX", CardType.RAINBOW),
                Card(218, "Rayquaza VMAX", CardType.RAINBOW),
                Card(219, "Duraludon VMAX", CardType.RAINBOW),
                Card(220, "Duraludon VMAX", CardType.RAINBOW),
                Card(221, "Aroma Lady", CardType.RAINBOW),
                Card(222, "Copycat", CardType.RAINBOW),
                Card(223, "Gordie", CardType.RAINBOW),
                Card(224, "Raihan", CardType.RAINBOW),
                Card(225, "Zinnia's Resolve", CardType.RAINBOW),
                Card(226, "Froslass", CardType.SECRET),
                Card(227, "Inteleon", CardType.SECRET),
                Card(228, "Cresselia", CardType.SECRET),
                Card(229, "Boost Shake", CardType.SECRET),
                Card(230, "Crystal Cave", CardType.SECRET),
                Card(231, "Full Face Guard", CardType.SECRET),
                Card(232, "Stormy Mountains", CardType.SECRET),
                Card(233, "Toy Catcher", CardType.SECRET),
                Card(234, "Turffield Stadium", CardType.SECRET),
                Card(235, "Lightning Energy", CardType.SECRET),
                Card(236, "Darkness Energy", CardType.SECRET),
                Card(237, "Metal Energy", CardType.SECRET)
            ),
            "Evolving%20Skies",
            listOf("jumbo", "promo", "psa", "japanese")
        )

        @JvmStatic
        fun main(args: Array<String>) {
            SeriesCollector().collect(collection)
        }
    }
}
