package com.mannanlive.ebay.collections.base

import com.mannanlive.ebay.collections.Card
import com.mannanlive.ebay.collections.CardType
import com.mannanlive.ebay.collections.SeriesCollection
import com.mannanlive.ebay.collections.SeriesCollector

class BaseSetTeamRocket {
    companion object {
        val collection = SeriesCollection(
            "TR",
            listOf(
                Card(1, "Dark Alakazam", CardType.NORMAL),
                Card(2, "Dark Arbok", CardType.NORMAL),
                Card(3, "Dark Blastoise", CardType.NORMAL),
                Card(4, "Dark Charizard", CardType.NORMAL),
                Card(5, "Dark Dragonite", CardType.NORMAL),
                Card(6, "Dark Dugtrio", CardType.NORMAL),
                Card(7, "Dark Golbat", CardType.NORMAL),
                Card(8, "Dark Gyarados", CardType.NORMAL),
                Card(9, "Dark Hypno", CardType.NORMAL),
                Card(10, "Dark Machamp", CardType.NORMAL),
                Card(11, "Dark Magneton", CardType.NORMAL),
                Card(12, "Dark Slowbro", CardType.NORMAL),
                Card(13, "Dark Vileplume", CardType.NORMAL),
                Card(14, "Dark Weezing", CardType.NORMAL),
                Card(15, "Here Comes Team Rocket", CardType.NORMAL),
                Card(16, "Rocket's Sneak Attack", CardType.NORMAL),
                Card(17, "Rainbow Energy", CardType.NORMAL),
                Card(18, "Dark Alakazam", CardType.NORMAL),
                Card(19, "Dark Arbok", CardType.NORMAL),
                Card(20, "Dark Blastoise", CardType.NORMAL),
                Card(21, "Dark Charizard", CardType.NORMAL),
                Card(22, "Dark Dragonite", CardType.NORMAL),
                Card(23, "Dark Dugtrio", CardType.NORMAL),
                Card(24, "Dark Golbat", CardType.NORMAL),
                Card(25, "Dark Gyarados", CardType.NORMAL),
                Card(26, "Dark Hypno", CardType.NORMAL),
                Card(27, "Dark Machamp", CardType.NORMAL),
                Card(28, "Dark Magneton", CardType.NORMAL),
                Card(29, "Dark Slowbro", CardType.NORMAL),
                Card(30, "Dark Vileplume", CardType.NORMAL),
                Card(31, "Dark Weezing", CardType.NORMAL),
                Card(32, "Dark Charmeleon", CardType.NORMAL),
                Card(33, "Dark Dragonair", CardType.NORMAL),
                Card(34, "Dark Electrode", CardType.NORMAL),
                Card(35, "Dark Flareon", CardType.NORMAL),
                Card(36, "Dark Gloom", CardType.NORMAL),
                Card(37, "Dark Golduck", CardType.NORMAL),
                Card(38, "Dark Jolteon", CardType.NORMAL),
                Card(39, "Dark Kadabra", CardType.NORMAL),
                Card(40, "Dark Machoke", CardType.NORMAL),
                Card(41, "Dark Muk", CardType.NORMAL),
                Card(42, "Dark Persian", CardType.NORMAL),
                Card(43, "Dark Primeape", CardType.NORMAL),
                Card(44, "Dark Rapidash", CardType.NORMAL),
                Card(45, "Dark Vaporeon", CardType.NORMAL),
                Card(46, "Dark Wartortle", CardType.NORMAL),
                Card(47, "Magikarp", CardType.NORMAL),
                Card(48, "Porygon", CardType.NORMAL),
                Card(49, "Abra", CardType.NORMAL),
                Card(50, "Charmander", CardType.NORMAL),
                Card(51, "Dark Raticate", CardType.NORMAL),
                Card(52, "Diglett", CardType.NORMAL),
                Card(53, "Dratini", CardType.NORMAL),
                Card(54, "Drowzee", CardType.NORMAL),
                Card(55, "Eevee", CardType.NORMAL),
                Card(56, "Ekans", CardType.NORMAL),
                Card(57, "Grimer", CardType.NORMAL),
                Card(58, "Koffing", CardType.NORMAL),
                Card(59, "Machop", CardType.NORMAL),
                Card(60, "Magnemite", CardType.NORMAL),
                Card(61, "Mankey", CardType.NORMAL),
                Card(62, "Meowth", CardType.NORMAL),
                Card(63, "Oddish", CardType.NORMAL),
                Card(64, "Ponyta", CardType.NORMAL),
                Card(65, "Psyduck", CardType.NORMAL),
                Card(66, "Rattata", CardType.NORMAL),
                Card(67, "Slowpoke", CardType.NORMAL),
                Card(68, "Squirtle", CardType.NORMAL),
                Card(69, "Voltorb", CardType.NORMAL),
                Card(70, "Zubat", CardType.NORMAL),
                Card(71, "Here Comes Team Rocket", CardType.NORMAL),
                Card(72, "Rocket's Sneak Attack", CardType.NORMAL),
                Card(73, "The Boss's Way", CardType.NORMAL),
                Card(74, "Challenge!", CardType.NORMAL),
                Card(75, "Digger", CardType.NORMAL),
                Card(76, "Imposter Oak's Revenge", CardType.NORMAL),
                Card(77, "Nightly Garbage Run", CardType.NORMAL),
                Card(78, "Goop Gas Attack", CardType.NORMAL),
                Card(79, "Sleep!", CardType.NORMAL),
                Card(80, "Rainbow Energy", CardType.NORMAL),
                Card(81, "Full Heal Energy", CardType.NORMAL),
                Card(82, "Potion Energy", CardType.NORMAL),
                Card(83, "Dark Raichu", CardType.NORMAL)
            ),
            "rocket",
            listOf("shadowless", "first", "edition", "psa", "bgs")
        )

        @JvmStatic
        fun main(args: Array<String>) = SeriesCollector().collect(collection)
    }
}
